---
engines:
  duplication:
    enabled: true
    exclude_paths:
      - 'final/font/**'
      - 'test/**'
exclude_paths:
  - 'debian/**'
  - 'doc/**'
  - 'icon/**'
  - 'logo/**'
  - 'm4/**'
  - 'scripts/**'

