name: "NetBSD build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2

    - name: Test on NetBSD 9.2
      uses: cross-platform-actions/action@v0.3.0
      with:
        operating_system: netbsd
        version: 9.2
        shell: bash
        run: |
          uname -a
          whoami
          pwd
          # https://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/index-all.html
          sudo pkgin install gcc10 automake-1.16.3 autoconf-2.71 autoconf-archive libtool pkgconf cppunit
          export AUTOCONF_VERSION=2.71
          export AUTOMAKE_VERSION=1.16
          g++ --version
          autoreconf -v --install --force
          ./configure --prefix=/usr
          make -j10

