name: "OpenBSD build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v3

    - name: Test on OpenBSD 7.1
      uses: cross-platform-actions/action@v0.6.2
      env:
        WORKSPACE_PATH: "${{ github.workspace }}"
      with:
        operating_system: openbsd
        version: '7.1'
        shell: bash
        run: |
          uname -a
          whoami
          pwd
          # http://ftp.openbsd.org/pub/OpenBSD/7.1/packages/amd64/
          sudo pkg_add gcc-11.2.0p2 g++-11.2.0p2 automake-1.16.3 autoconf-2.71 autoconf-archive libtool pkgconf cppunit
          export CXX=eg++
          export AUTOCONF_VERSION=2.71
          export AUTOMAKE_VERSION=1.16
          eg++ --version
          autoreconf -v --install --force
          ./configure --prefix=/usr
          make -j10

