name: "Solaris build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 2'

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Repository checkout
      uses: actions/checkout@v3

    - name: Test on Solaris 11.4
      uses: vmactions/solaris-vm@v0
      with:
        prepare: |
          pkg publisher solaris
          echo "========= before ggc install ========="
          pkg install -v gcc-11
          test -f /usr/bin/gcc || test -f /usr/gcc/11/bin/gcc && ln -s ../gcc/11/bin/gcc /usr/bin/gcc
          test -f /usr/bin/g++ || test -f /usr/gcc/11/bin/g++ && ln -s ../gcc/11/bin/g++ /usr/bin/g++
          /usr/bin/g++ -dumpfullversion -dumpversion
          echo "========= after ggc install ========="
          pkgutil -y -i automake autoconf autoconf_archive libtool pkgconfig libcppunit1_12_1 libcppunit_dev gsed ggrep
        mem: 4096
        run: |
          uname -a
          whoami
          pwd
          cat /etc/release
          PATH=/opt/csw/bin:$PATH
          export PATH
          autoreconf -v --install --force
          ./configure --prefix=/usr
          CXX="/usr/gcc/11/bin/g++" gmake V=1 -j$(nproc)

